# Data Preprocessing and Training Data Development

## Project Overview

The goal of this section is to prepare the dataset for machine learning modeling. The preprocessing steps include removing unnecessary variables, scaling numerical features, converting categorical variables into dummy variables, and splitting the dataset into training and testing sets.

## Import libraries

## Load Dataset

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("cleaned_shipping_data.csv")

df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,1,D,Flight,4,2,177,3,low,F,44,1233,1
1,2,F,Flight,4,5,216,2,low,M,59,3088,1
2,3,A,Flight,2,2,183,4,low,M,48,3374,1
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1

In [3]:
df = df.drop("ID", axis=1)

df.head()

,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N
0,D,Flight,4,2,177,3,low,F,44,1233,1
1,F,Flight,4,5,216,2,low,M,59,3088,1
2,A,Flight,2,2,183,4,low,M,48,3374,1
3,B,Flight,3,3,176,4,medium,M,10,1177,1
4,C,Flight,2,2,184,3,medium,F,46,2484,1

The ID column is removed because it is only an identifier and does not contribute useful information for predicting the target variable.

In [4]:
X = df.drop("Reached.on.Time_Y.N", axis=1)
y = df["Reached.on.Time_Y.N"]

## Feature Scaling

Feature scaling is applied to ensure that numerical variables contribute equally to the machine learning model. Standardization transforms features so they have a mean of zero and a standard deviation of one, preventing variables with larger magnitudes from dominating the model.

In [5]:
num_cols = X.select_dtypes(include=["int64","float64"]).columns
cat_cols = X.select_dtypes(include=["object"]).columns

print("Numerical columns:", num_cols)
print("Categorical columns:", cat_cols)

Numerical columns: Index(['Customer_care_calls', 'Customer_rating', 'Cost_of_the_Product',
       'Prior_purchases', 'Discount_offered', 'Weight_in_gms'],
      dtype='object')
Categorical columns: Index(['Warehouse_block', 'Mode_of_Shipment', 'Product_importance', 'Gender'], dtype='object')

## Apply StandardScaler to Numerical Features

In [6]:
scaler = StandardScaler()

X_num_scaled = pd.DataFrame(
    scaler.fit_transform(X[num_cols]),
    columns=num_cols
)

## Create Dummy Variables for Categorical Features

In [7]:
if len(cat_cols) > 0:
    X_cat = pd.get_dummies(X[cat_cols], drop_first=True)
else:
    X_cat = pd.DataFrame()

## Combine Processed Features

In [8]:
X_processed = pd.concat([X_num_scaled, X_cat], axis=1)

X_processed.head()

,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,Warehouse_block_B,Warehouse_block_C,Warehouse_block_D,Warehouse_block_F,Mode_of_Shipment_Road,Mode_of_Shipment_Ship,Product_importance_low,Product_importance_medium,Gender_M
0,-0.047711,-0.700755,-0.690722,-0.372735,1.889983,-1.468240,False,False,True,False,False,False,True,False,False
1,-0.047711,1.421578,0.120746,-1.029424,2.815636,-0.333893,False,False,False,True,False,False,True,False,True
2,-1.799887,-0.700755,-0.565881,0.283954,2.136824,-0.159002,False,False,False,False,False,False,True,False,True
3,-0.923799,0.006689,-0.711529,0.283954,-0.208162,-1.502484,True,False,False,False,False,False,False,True,True
4,-1.799887,-0.700755,-0.545074,-0.372735,2.013404,-0.703244,False,True,False,False,False,False,False,True,False

## Train-Test Split 
The dataset is split into training and testing sets to allow the model to learn patterns from the training data and evaluate performance on unseen data.

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

### Verification Step

In [10]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (8799, 10)
X_test shape: (2200, 10)
y_train shape: (8799,)
y_test shape: (2200,)

## Summary

The dataset has been successfully preprocessed for modeling. The ID column was removed to avoid unnecessary noise, numerical features were standardized using StandardScaler, and categorical variables were converted into dummy variables. Finally, the processed dataset was split into training and testing sets to prepare for machine learning model development.